### ISSUE TITLE
Implied feature: User creation & Authentication

### ISSUE THREAD

**Issue by thecatwasnot** [markedli/markedli#1]
Not yet explicitly defined in the documentation, we'll need an authentication system.  Devise is a nice set of tools on top of a rack based authentication solution, as it's likely we'll need a full api, devise hooks into the rack stack and provides access to authentication across the board.

**Comment by anathomical** [comment]
We've been using Devise at work on top of a Mongo(id) stack, and it's performed very well (and seamlessly), so I'm all in favor of using it for this.

**Comment by thecatwasnot** [comment]
Working version of user authentication with devise
https://github.com/thecatwasnot/markedli/tree/authentication

Working on an oauth implementation now, going to use cucumber for api acceptance testing for the moment, simply because it means all the acceptance tests are in one place.

**Comment by thecatwasnot** [comment]
So I've tried, twice now to get oauth-plugin to play nicely with mongoid and it's not going as well, or as quickly as I'd want.  I think the best option is actually to roll our own provider that way it can be fully tested and we'd be more familiar with the actual code.  I'm going to start this and see how it goes.

**Comment by thecatwasnot** [comment]
Progress here: https://github.com/thecatwasnot/markedli/tree/authentication
based on
http://tools.ietf.org/html/draft-ietf-oauth-v2-22
http://www.railsatwork.com/2010/10/implementing-oauth-provider-part-1.html
All I have left is to hook access_token param into devise token authentication, then devise/warden will work with both web & oauth :)
Also, the goal at this point is to have enough of a framework  that other features can be built in parallel, this is in no way a complete solution.
